[colors.bright]
black = "#5b6268"
blue = "#3071db"
cyan = "#46d9ff"
green = "#4db5bd"
magenta = "#a9a1e1"
red = "#da8548"
white = "#dfdfdf"
yellow = "#ecbe7b"

[colors.cursor]
cursor = "#528bff"
text = "CellBackground"

[colors.normal]
black = "#282c34"
blue = "#51afef"
cyan = "#46d9ff"
green = "#98be65"
magenta = "#c678dd"
red = "#ff6c6b"
white = "#bbc2cf"
yellow = "#ecbe7b"

[colors.primary]
background = "#282c34"
foreground = "#bbc2cf"

[colors.selection]
background = "#3e4451"
text = "CellForeground"

[font]
size = 11