theme = "onedark"

[editor]
scrolloff = 10
mouse = false
middle-click-paste = false
line-number = "relative"
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.whitespace.render]
tab = "all"

[keys.normal]
X = "extend_line_above"