# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float on, match:class ^(kitty)$, match:title ^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Privacy filter
windowrule = no_screen_share on, match:class ^(discord)$

# Discord on workspace 10
windowrule = workspace 10, match:class ^(discord)$

# Center new floating windows
windowrule = center on, match:float 1

# For any dialog windows (you can customize the class name)
windowrule = float on, match:class ^(.*dialog.*)$
windowrule = center on, match:class ^(.*dialog.*)$

# Kitty terminal settings (manage opacity on hypr instead of kitty so it doesn't break the gnome colors setup)
windowrule = opacity 0.8 override, match:class ^(kitty)$

# NM Connection Editor settings
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = center on, match:class ^(nm-connection-editor)$
windowrule = size 800 600, match:class ^(nm-connection-editor)$

# Pavucontrol settings
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = center on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = size 800 600, match:class ^(org.pulseaudio.pavucontrol)$

# Blur wlogout
layerrule = blur on, match:namespace logout_dialog

layerrule = blur on, match:namespace rofi
layerrule = animation popin 95%, match:namespace rofi
